# Generated by Django 2.0rc1 on 2017-12-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadlog',
            name='filename',
            field=models.FilePathField(editable=False, path='/home/jgsogo/Programming/presura/data/ine/'),
        ),
    ]
