# Generated by Django 2.0rc1 on 2017-11-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downloadlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='downloadlog',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='downloadlog',
            name='filename',
            field=models.FilePathField(default='a', editable=False, path='C:\\Javi\\dev\\presura\\data\\ine'),
            preserve_default=False,
        ),
    ]
