# Generated by Django 2.0rc1 on 2017-12-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ine', '0002_auto_20171203_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadlog',
            name='filename',
            field=models.FilePathField(editable=False, path='C:\\Javi\\dev\\presura\\data\\ine'),
        ),
    ]
