# Generated by Django 2.0rc1 on 2017-11-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ine', '0002_auto_20171126_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='ext',
            field=models.CharField(default='rar', max_length=12, verbose_name='extension'),
            preserve_default=False,
        ),
    ]
