# Generated by Django 2.0rc1 on 2017-11-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ine', '0003_resource_ext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='ext',
        ),
        migrations.AddField(
            model_name='resource',
            name='importer',
            field=models.CharField(default='', max_length=20, verbose_name='externsion'),
            preserve_default=False,
        ),
    ]
