# Generated by Django 2.0rc1 on 2017-12-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ine', '0003_auto_20171206_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='importer',
            field=models.CharField(blank=True, choices=[('mapas_municipales', 'mapas_municipales'), ('padron_municipal', 'padron_municipal')], max_length=20, null=True, verbose_name='importer'),
        ),
    ]
