# Generated by Django 2.0rc1 on 2017-11-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ine', '0004_auto_20171126_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='importer',
            field=models.CharField(max_length=20, verbose_name='importer'),
        ),
    ]
