# Generated by Django 2.0rc1 on 2017-11-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ine', '0005_auto_20171126_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadlog',
            name='filename',
            field=models.FilePathField(editable=False, path='/home/jgsogo/Programming/presura/data/ine/'),
        ),
    ]
