# Generated by Django 2.0rc1 on 2017-12-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ine', '0006_auto_20171128_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadlog',
            name='filename',
            field=models.FilePathField(editable=False, path='C:\\Javi\\dev\\presura\\data\\ine'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='importer',
            field=models.CharField(blank=True, choices=[('mapas_municipales', 'mapas_municipales')], max_length=20, null=True, verbose_name='importer'),
        ),
    ]
