# Generated by Django 2.0rc1 on 2017-11-26 20:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCAA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField()),
                ('perimeter', models.FloatField()),
                ('bbox', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('points', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField()),
                ('perimeter', models.FloatField()),
                ('bbox', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('points', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField()),
                ('perimeter', models.FloatField()),
                ('bbox', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('points', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('name', models.CharField(max_length=255)),
                ('ccaa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carto.CCAA')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField()),
                ('perimeter', models.FloatField()),
                ('bbox', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('points', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('name', models.CharField(max_length=120)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carto.CCAA')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='municipality',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carto.Province'),
        ),
        migrations.AddField(
            model_name='ccaa',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carto.Country'),
        ),
    ]
