# Generated by Django 2.0rc1 on 2017-12-07 10:49

import datasets.utils.plottable
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('spatial_reference', models.IntegerField(choices=[(4326, 'WGS84'), (23030, 'Proyección UTM ED50 Huso 30 N')], default=4326)),
                ('draw_type', models.IntegerField(choices=[(0, 'Line'), (1, 'Filled')], default=0)),
                ('color_pattern', models.IntegerField(choices=[(0, 'Random')], default=0)),
            ],
            bases=(datasets.utils.plottable.Plottable, models.Model),
        ),
    ]
