# Generated by Django 2.0rc1 on 2017-11-26 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ccaa',
            name='bbox',
        ),
        migrations.RemoveField(
            model_name='country',
            name='bbox',
        ),
        migrations.RemoveField(
            model_name='municipality',
            name='bbox',
        ),
        migrations.RemoveField(
            model_name='province',
            name='bbox',
        ),
    ]
