# Generated by Django 2.0rc1 on 2017-12-02 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        ('carto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.DataSet'),
        ),
        migrations.AddField(
            model_name='province',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carto.CCAA'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='ccaa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carto.CCAA'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.DataSet'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carto.Province'),
        ),
        migrations.AddField(
            model_name='country',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.DataSet'),
        ),
        migrations.AddField(
            model_name='ccaa',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carto.Country'),
        ),
        migrations.AddField(
            model_name='ccaa',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.DataSet'),
        ),
    ]
