# Generated by Django 2.0rc1 on 2017-12-07 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0003_auto_20171207_1258'),
        ('carto', '0002_layer_dataset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layer',
            old_name='dataset',
            new_name='basemap',
        ),
        migrations.AddField(
            model_name='layer',
            name='category',
            field=models.CharField(blank=True, help_text='Category to plot', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='datasets.INEPadron'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layer',
            name='period',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
