# Generated by Django 2.0rc1 on 2017-12-02 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0001_initial'),
        ('carto', '0003_auto_20171128_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccaa',
            name='dataset',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='datasets.DataSet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='dataset',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='datasets.DataSet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipality',
            name='dataset',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='datasets.DataSet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='province',
            name='dataset',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='datasets.DataSet'),
            preserve_default=False,
        ),
    ]
