# Generated by Django 2.0rc1 on 2017-12-07 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0004_auto_20171207_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='color_pattern',
        ),
    ]
