# Generated by Django 2.0rc1 on 2017-12-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0005_remove_layer_color_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='per_area_unit',
            field=models.BooleanField(default=False),
        ),
    ]
