# Generated by Django 2.0rc1 on 2017-12-08 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0006_layer_per_area_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('tile_map_base', models.CharField(blank=True, choices=[('Cache', 'Cache'), ('Carto_Dark', 'Carto_Dark'), ('Carto_Dark_Labels', 'Carto_Dark_Labels'), ('Carto_Dark_No_Labels', 'Carto_Dark_No_Labels'), ('Carto_Light', 'Carto_Light'), ('Carto_Light_Labels', 'Carto_Light_Labels'), ('Carto_Light_No_Labels', 'Carto_Light_No_Labels'), ('OSM', 'OSM'), ('Stamen_Terrain', 'Stamen_Terrain'), ('Stamen_Terrain_Background', 'Stamen_Terrain_Background'), ('Stamen_Terrain_Labels', 'Stamen_Terrain_Labels'), ('Stamen_Terrain_Lines', 'Stamen_Terrain_Lines'), ('Stamen_Toner', 'Stamen_Toner'), ('Stamen_Toner_Background', 'Stamen_Toner_Background'), ('Stamen_Toner_Hybrid', 'Stamen_Toner_Hybrid'), ('Stamen_Toner_Labels', 'Stamen_Toner_Labels'), ('Stamen_Toner_Lines', 'Stamen_Toner_Lines'), ('Stamen_Toner_Lite', 'Stamen_Toner_Lite'), ('Stamen_Watercolour', 'Stamen_Watercolour'), ('Tiles', 'Tiles'), ('_Image', '_Image'), ('_TilesExecutor', '_TilesExecutor'), ('__builtins__', '__builtins__'), ('__cached__', '__cached__'), ('__doc__', '__doc__'), ('__file__', '__file__'), ('__loader__', '__loader__'), ('__name__', '__name__'), ('__package__', '__package__'), ('__spec__', '__spec__'), ('_cache', '_cache'), ('_datetime', '_datetime'), ('_get_cache', '_get_cache'), ('_io', '_io'), ('_logging', '_logging'), ('_os', '_os'), ('_requests', '_requests'), ('_sqcache', '_sqcache'), ('close', 'close'), ('get_cache', 'get_cache'), ('init', 'init')], max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MapLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('z_index', models.PositiveSmallIntegerField(default=0)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='carto.Map')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carto.Map')),
            ],
        ),
    ]
