# Generated by Django 2.0rc1 on 2017-12-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0007_map_maplayer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='tile_map_base',
        ),
        migrations.AddField(
            model_name='map',
            name='_tile_map_base',
            field=models.CharField(blank=True, choices=[('STAMEN_TONER_Labels', 'STAMEN_TONER_Labels'), ('STAMEN_TONER_Lite', 'STAMEN_TONER_Lite'), ('STAMEN_TONER', 'STAMEN_TONER'), ('CARTO_LIGHT', 'CARTO_LIGHT'), ('STAMEN_TERRAIN_Lines', 'STAMEN_TERRAIN_Lines'), ('STAMEN_TERRAIN', 'STAMEN_TERRAIN'), ('CARTO_DARK_LABELS', 'CARTO_DARK_LABELS'), ('CARTO_LIGHT_NOLABELS', 'CARTO_LIGHT_NOLABELS'), ('STAMEN_TONER_Hybrid', 'STAMEN_TONER_Hybrid'), ('CARTO_DARK_NOLABELS', 'CARTO_DARK_NOLABELS'), ('STAMEN_TERRAIN_Labels', 'STAMEN_TERRAIN_Labels'), ('CARTO_DARK', 'CARTO_DARK'), ('STAMEN_TONER_Background', 'STAMEN_TONER_Background'), ('OSM', 'OSM'), ('STAMEN_TERRAIN_Background', 'STAMEN_TERRAIN_Background'), ('STAMEN_WATERCOLOUR', 'STAMEN_WATERCOLOUR'), ('STAMEN_TONER_Lines', 'STAMEN_TONER_Lines'), ('CARTO_LIGHT_LABELS', 'CARTO_LIGHT_LABELS')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plotables/'),
        ),
    ]
