# Generated by Django 2.0rc1 on 2017-12-08 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0008_auto_20171208_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='_tile_map_base',
            field=models.CharField(blank=True, choices=[('STAMEN_TONER', 'STAMEN_TONER'), ('STAMEN_WATERCOLOUR', 'STAMEN_WATERCOLOUR'), ('CARTO_LIGHT_NOLABELS', 'CARTO_LIGHT_NOLABELS'), ('STAMEN_TONER_Lite', 'STAMEN_TONER_Lite'), ('STAMEN_TERRAIN', 'STAMEN_TERRAIN'), ('STAMEN_TERRAIN_Lines', 'STAMEN_TERRAIN_Lines'), ('OSM', 'OSM'), ('CARTO_DARK', 'CARTO_DARK'), ('STAMEN_TERRAIN_Labels', 'STAMEN_TERRAIN_Labels'), ('CARTO_DARK_NOLABELS', 'CARTO_DARK_NOLABELS'), ('STAMEN_TONER_Background', 'STAMEN_TONER_Background'), ('CARTO_LIGHT', 'CARTO_LIGHT'), ('CARTO_DARK_LABELS', 'CARTO_DARK_LABELS'), ('STAMEN_TONER_Lines', 'STAMEN_TONER_Lines'), ('CARTO_LIGHT_LABELS', 'CARTO_LIGHT_LABELS'), ('STAMEN_TERRAIN_Background', 'STAMEN_TERRAIN_Background'), ('STAMEN_TONER_Labels', 'STAMEN_TONER_Labels'), ('STAMEN_TONER_Hybrid', 'STAMEN_TONER_Hybrid')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carto.Layer'),
        ),
    ]
