# Generated by Django 2.0rc1 on 2017-12-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0011_auto_20171209_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='basemap_width',
            field=models.PositiveIntegerField(default=600),
        ),
        migrations.AddField(
            model_name='map',
            name='dpi',
            field=models.PositiveIntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='map',
            name='_tile_map_base',
            field=models.CharField(blank=True, choices=[('STAMEN_TONER_Labels', 'STAMEN_TONER_Labels'), ('CARTO_LIGHT', 'CARTO_LIGHT'), ('STAMEN_TERRAIN', 'STAMEN_TERRAIN'), ('STAMEN_TONER_Lite', 'STAMEN_TONER_Lite'), ('CARTO_DARK_NOLABELS', 'CARTO_DARK_NOLABELS'), ('CARTO_DARK_LABELS', 'CARTO_DARK_LABELS'), ('STAMEN_TERRAIN_Background', 'STAMEN_TERRAIN_Background'), ('STAMEN_TONER_Lines', 'STAMEN_TONER_Lines'), ('CARTO_DARK', 'CARTO_DARK'), ('STAMEN_TONER_Background', 'STAMEN_TONER_Background'), ('STAMEN_TONER_Hybrid', 'STAMEN_TONER_Hybrid'), ('STAMEN_WATERCOLOUR', 'STAMEN_WATERCOLOUR'), ('STAMEN_TERRAIN_Labels', 'STAMEN_TERRAIN_Labels'), ('STAMEN_TONER', 'STAMEN_TONER'), ('OSM', 'OSM'), ('STAMEN_TERRAIN_Lines', 'STAMEN_TERRAIN_Lines'), ('CARTO_LIGHT_LABELS', 'CARTO_LIGHT_LABELS'), ('CARTO_LIGHT_NOLABELS', 'CARTO_LIGHT_NOLABELS')], max_length=64, null=True),
        ),
    ]
