# Generated by Django 2.0rc1 on 2017-12-09 09:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0012_auto_20171209_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='bbox',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='map',
            name='_tile_map_base',
            field=models.CharField(blank=True, choices=[('STAMEN_TERRAIN_Background', 'STAMEN_TERRAIN_Background'), ('STAMEN_TERRAIN_Lines', 'STAMEN_TERRAIN_Lines'), ('STAMEN_TERRAIN_Labels', 'STAMEN_TERRAIN_Labels'), ('STAMEN_TONER_Hybrid', 'STAMEN_TONER_Hybrid'), ('STAMEN_TERRAIN', 'STAMEN_TERRAIN'), ('CARTO_DARK_NOLABELS', 'CARTO_DARK_NOLABELS'), ('STAMEN_TONER_Lines', 'STAMEN_TONER_Lines'), ('CARTO_LIGHT_NOLABELS', 'CARTO_LIGHT_NOLABELS'), ('STAMEN_TONER_Background', 'STAMEN_TONER_Background'), ('OSM', 'OSM'), ('CARTO_DARK_LABELS', 'CARTO_DARK_LABELS'), ('STAMEN_WATERCOLOUR', 'STAMEN_WATERCOLOUR'), ('CARTO_LIGHT_LABELS', 'CARTO_LIGHT_LABELS'), ('STAMEN_TONER', 'STAMEN_TONER'), ('STAMEN_TONER_Labels', 'STAMEN_TONER_Labels'), ('CARTO_DARK', 'CARTO_DARK'), ('STAMEN_TONER_Lite', 'STAMEN_TONER_Lite'), ('CARTO_LIGHT', 'CARTO_LIGHT')], max_length=64, null=True),
        ),
    ]
